//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _300px_Atari2600a {
            get {
                object obj = ResourceManager.GetObject("300px-Atari2600a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Arcade_Classics_Sideart_r2 {
            get {
                object obj = ResourceManager.GetObject("Arcade-Classics-Sideart-r2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap atari_2600_machine {
            get {
                object obj = ResourceManager.GetObject("atari_2600_machine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Atari_logo {
            get {
                object obj = ResourceManager.GetObject("Atari_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap collage_bla {
            get {
                object obj = ResourceManager.GetObject("collage-bla", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap collage_bla1 {
            get {
                object obj = ResourceManager.GetObject("collage-bla1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap collage_bla2 {
            get {
                object obj = ResourceManager.GetObject("collage-bla2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap e3_2005_mario_luigi_2_20050515003257134 {
            get {
                object obj = ResourceManager.GetObject("e3-2005-mario-luigi-2-20050515003257134", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap e3_2005_mario_luigi_2_200505150032571341 {
            get {
                object obj = ResourceManager.GetObject("e3-2005-mario-luigi-2-200505150032571341", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap e3_2005_mario_luigi_2_200505150032571342 {
            get {
                object obj = ResourceManager.GetObject("e3-2005-mario-luigi-2-200505150032571342", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap e3_2005_mario_luigi_2_200505150032571343 {
            get {
                object obj = ResourceManager.GetObject("e3-2005-mario-luigi-2-200505150032571343", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap heading {
            get {
                object obj = ResourceManager.GetObject("heading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Logo_SEGA_Web {
            get {
                object obj = ResourceManager.GetObject("Logo SEGA_Web", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NES {
            get {
                object obj = ResourceManager.GetObject("NES", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NES1 {
            get {
                object obj = ResourceManager.GetObject("NES1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nintendo_game_boy_original_250 {
            get {
                object obj = ResourceManager.GetObject("nintendo_game_boy_original_250", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nintendo_logo_400_400 {
            get {
                object obj = ResourceManager.GetObject("nintendo_logo-400-400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nintendo_logo_400_4001 {
            get {
                object obj = ResourceManager.GetObject("nintendo_logo-400-4001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NintendoWallpaperClear {
            get {
                object obj = ResourceManager.GetObject("NintendoWallpaperClear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NintendoWallpaperClear2 {
            get {
                object obj = ResourceManager.GetObject("NintendoWallpaperClear2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NintendoWallpaperClear3 {
            get {
                object obj = ResourceManager.GetObject("NintendoWallpaperClear3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NintendoWallpaperClear4 {
            get {
                object obj = ResourceManager.GetObject("NintendoWallpaperClear4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap playstation {
            get {
                object obj = ResourceManager.GetObject("playstation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PlayStationConsole_bkg_transparent {
            get {
                object obj = ResourceManager.GetObject("PlayStationConsole_bkg-transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap realmario {
            get {
                object obj = ResourceManager.GetObject("realmario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap realmario1 {
            get {
                object obj = ResourceManager.GetObject("realmario1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sega_genesis_2s {
            get {
                object obj = ResourceManager.GetObject("sega_genesis_2s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sega_genesis_game_console {
            get {
                object obj = ResourceManager.GetObject("sega-genesis-game-console", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sega_genesis_game_console1 {
            get {
                object obj = ResourceManager.GetObject("sega-genesis-game-console1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sega_master_system_qjgenth {
            get {
                object obj = ResourceManager.GetObject("sega-master-system_qjgenth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sega_qjpreviewth {
            get {
                object obj = ResourceManager.GetObject("Sega_qjpreviewth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SEGA_SYSTEM {
            get {
                object obj = ResourceManager.GetObject("SEGA_SYSTEM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap snes_us {
            get {
                object obj = ResourceManager.GetObject("snes-us", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sonictailsoo3 {
            get {
                object obj = ResourceManager.GetObject("sonictailsoo3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sticks {
            get {
                object obj = ResourceManager.GetObject("sticks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Super_Nintendo_Entertainment_System_USA {
            get {
                object obj = ResourceManager.GetObject("Super_Nintendo_Entertainment_System-USA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
